<?php
add_action( 'acf/init', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_6047f50a53531',
	'title' => 'Timeline',
	'fields' => array(
		array(
			'key' => 'field_6047f5168c61f',
			'label' => 'Events',
			'name' => 'dates',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => 'Add timeline events here.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Event',
			'sub_fields' => array(
				array(
					'key' => 'field_6047f54c8c620',
					'label' => 'Event Date',
					'name' => 'date',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'Enter the event date here.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.3',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'allow_in_bindings' => 1,
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6047f5168c61f',
				),
				array(
					'key' => 'field_69aef29c76b86',
					'label' => 'Icon',
					'name' => 'icon',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => 'Use either pngs or svg files here. Square images work best.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.3',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => 'svg, png',
					'allow_in_bindings' => 1,
					'preview_size' => 'medium',
					'parent_repeater' => 'field_6047f5168c61f',
				),
				array(
					'key' => 'field_69aef2b176b87',
					'label' => 'Icon Background Color',
					'name' => 'icon_background_color',
					'aria-label' => '',
					'type' => 'color_picker',
					'instructions' => 'Choose the background color behind the icon.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '33.3',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'enable_opacity' => 0,
					'return_format' => 'string',
					'allow_in_bindings' => 1,
					'show_custom_palette' => 0,
					'show_color_wheel' => 1,
					'custom_palette_source' => '',
					'palette_colors' => '',
					'parent_repeater' => 'field_6047f5168c61f',
				),
				array(
					'key' => 'field_6047f5968c621',
					'label' => 'Content',
					'name' => 'content',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => 'Add event content here; text, images and video etc.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'allow_in_bindings' => 1,
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
					'parent_repeater' => 'field_6047f5168c61f',
				),
			),
			'rows_per_page' => 20,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'timeline',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'display_title' => '',
) );
} );
?>